
# Data 101 — Module 5, Session 2
## Pandas Basics (Demo Notebook)

This notebook follows the Session 2 slide outline:
- Importing Pandas
- Series and DataFrames
- Loading a CSV
- Selecting columns and rows (`loc` vs `iloc`)
- Column slicing with `loc`
- Boolean filtering
- Modifying data
- Summary statistics and grouping

## Import Pandas

In [2]:
import pandas as pd
import numpy as np

print("pandas:", pd.__version__)
print("numpy:", np.__version__)

pandas: 3.0.1
numpy: 2.4.2

## Series

In [3]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
display(s)

a    10
b    20
c    30
dtype: int64

In [7]:
print("Access by label:", s.loc["b"])

Access by label: 20

In [8]:
print("Access by position:", s.iloc[1])

Access by position: 20

## DataFrame

In [9]:
data = {"Name": ["Alex", "Jamie"], "GPA": [3.4, 3.8]}
df_small = pd.DataFrame(data)
display(df_small)

    Name  GPA
0   Alex  3.4
1  Jamie  3.8

## Load Data from CSV

In [10]:
# A sample CSV is saved at: ./data/students.csv
df = pd.read_csv("./data/students.csv")
display(df.head())

     Name Gender    Major  GPA  Hours_Studied
0    Alex      F       CS  3.4             10
1   Jamie      M     Math  3.8             15
2  Jordan      F       CS  3.1              8
3  Taylor      M  Physics  2.9             12
4   Riley      F     Math  3.6              9

In [11]:
df

     Name Gender    Major  GPA  Hours_Studied
0    Alex      F       CS  3.4             10
1   Jamie      M     Math  3.8             15
2  Jordan      F       CS  3.1              8
3  Taylor      M  Physics  2.9             12
4   Riley      F     Math  3.6              9
5   Casey      M       CS  2.5              5
6  Morgan      F  Physics  3.2             11

In [12]:
print("\nInfo:")
display(df.info())

Info:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           7 non-null      str
 1   Gender         7 non-null      str
 2   Major          7 non-null      str
 3   GPA            7 non-null      float64
 4   Hours_Studied  7 non-null      int64
dtypes: float64(1), int64(1), str(3)
memory usage: 412.0 bytes

None

In [13]:
print("\nDescribe:")
display(df.describe())

Describe:

            GPA  Hours_Studied
count  7.000000       7.000000
mean   3.214286      10.000000
std    0.437526       3.162278
min    2.500000       5.000000
25%    3.000000       8.500000
50%    3.200000      10.000000
75%    3.500000      11.500000
max    3.800000      15.000000

In [14]:
print("\nDescribe:")
display(df.describe(include="all"))

Describe:

        Name Gender Major       GPA  Hours_Studied
count      7      7     7  7.000000       7.000000
unique     7      2     3       NaN            NaN
top     Alex      F    CS       NaN            NaN
freq       1      4     3       NaN            NaN
mean     NaN    NaN   NaN  3.214286      10.000000
std      NaN    NaN   NaN  0.437526       3.162278
min      NaN    NaN   NaN  2.500000       5.000000
25%      NaN    NaN   NaN  3.000000       8.500000
50%      NaN    NaN   NaN  3.200000      10.000000
75%      NaN    NaN   NaN  3.500000      11.500000
max      NaN    NaN   NaN  3.800000      15.000000

## Selecting Columns

In [15]:
gpa_series = df["GPA"]
display(gpa_series.head())

0    3.4
1    3.8
2    3.1
3    2.9
4    3.6
Name: GPA, dtype: float64

In [16]:
name_gpa_df = df[["Name", "GPA"]]
display(name_gpa_df.head())

     Name  GPA
0    Alex  3.4
1   Jamie  3.8
2  Jordan  3.1
3  Taylor  2.9
4   Riley  3.6

## Selecting Rows with `.loc` (label-based)

In [17]:

df = df.reset_index(drop=True)

row_label_0 = df.loc[0]
display(row_label_0)

Name             Alex
Gender              F
Major              CS
GPA               3.4
Hours_Studied      10
Name: 0, dtype: object

In [18]:
rows_0_to_2 = df.loc[0:2]
display(rows_0_to_2)

     Name Gender Major  GPA  Hours_Studied
0    Alex      F    CS  3.4             10
1   Jamie      M  Math  3.8             15
2  Jordan      F    CS  3.1              8

In [19]:
rows_0_to_2 = df.iloc[0:2]
display(rows_0_to_2)

    Name Gender Major  GPA  Hours_Studied
0   Alex      F    CS  3.4             10
1  Jamie      M  Math  3.8             15

In [20]:
gpa_all_rows = df.loc[:, "GPA"]
display(gpa_all_rows.head())

0    3.4
1    3.8
2    3.1
3    2.9
4    3.6
Name: GPA, dtype: float64

## Selecting Rows with `.iloc` (position-based)

In [ ]:

first_row = df.iloc[0]
first_three_rows = df.iloc[0:3]
second_column_all_rows = df.iloc[:, 1]

display(first_row)
display(first_three_rows)
display(second_column_all_rows.head())

Name             Alex
Gender              F
Major              CS
GPA               3.4
Hours_Studied      10
Name: 0, dtype: object

     Name Gender Major  GPA  Hours_Studied
0    Alex      F    CS  3.4             10
1   Jamie      M  Math  3.8             15
2  Jordan      F    CS  3.1              8

0    F
1    M
2    F
3    M
4    F
Name: Gender, dtype: str

## `loc` vs `iloc` example

In [23]:

example_loc = df.loc[2, "GPA"]   # row label 2, column "GPA"
example_iloc = df.iloc[2, 3]     # third row, fourth column (0-based indexing)
print("df.loc[2, 'GPA']  ->", example_loc)
print("df.iloc[2, 3]     ->", example_iloc)

df.loc[2, 'GPA']  -> 3.1
df.iloc[2, 3]     -> 3.1

## Column Slicing with `loc` and a common pitfall

In [24]:
one_col = df.loc[:, "GPA"]
display(one_col.head())

0    3.4
1    3.8
2    3.1
3    2.9
4    3.6
Name: GPA, dtype: float64

In [25]:
multi_cols = df.loc[:, ["Name", "GPA"]]
display(multi_cols.head())

     Name  GPA
0    Alex  3.4
1   Jamie  3.8
2  Jordan  3.1
3  Taylor  2.9
4   Riley  3.6

In [26]:
range_cols = df.loc[:, "Name":"GPA"]
display(range_cols.head())

     Name Gender    Major  GPA
0    Alex      F       CS  3.4
1   Jamie      M     Math  3.8
2  Jordan      F       CS  3.1
3  Taylor      M  Physics  2.9
4   Riley      F     Math  3.6

In [27]:
bad = df[:, "GPA"]

InvalidIndexError: (slice(None, None, None), 'GPA')

In [28]:
try:
    bad = df[:, "GPA"]
except Exception as e:
    print("Using df[:, 'GPA'] raises ->", repr(e))

Using df[:, 'GPA'] raises -> InvalidIndexError((slice(None, None, None), 'GPA'))

## Boolean Filtering

In [30]:
df["GPA"]

0    3.4
1    3.8
2    3.1
3    2.9
4    3.6
5    2.5
6    3.2
Name: GPA, dtype: float64

In [31]:
df["GPA"] > 3.5

0    False
1     True
2    False
3    False
4     True
5    False
6    False
Name: GPA, dtype: bool

In [ ]:

high_gpa = df[df["GPA"] > 3.5]
display(high_gpa)

    Name Gender Major  GPA  Hours_Studied
1  Jamie      M  Math  3.8             15
4  Riley      F  Math  3.6              9

In [32]:
cs_or_math = df[(df["Major"] == "CS") | (df["Major"] == "Math")]
display(cs_or_math)

     Name Gender Major  GPA  Hours_Studied
0    Alex      F    CS  3.4             10
1   Jamie      M  Math  3.8             15
2  Jordan      F    CS  3.1              8
4   Riley      F  Math  3.6              9
5   Casey      M    CS  2.5              5

## Modifying Data

In [33]:

df["Passed"] = df["GPA"] >= 2.0
df["GPA_rounded"] = df["GPA"].round(0)
display(df.head())

     Name Gender    Major  GPA  Hours_Studied  Passed  GPA_rounded
0    Alex      F       CS  3.4             10    True          3.0
1   Jamie      M     Math  3.8             15    True          4.0
2  Jordan      F       CS  3.1              8    True          3.0
3  Taylor      M  Physics  2.9             12    True          3.0
4   Riley      F     Math  3.6              9    True          4.0

## Summary Statistics

In [34]:

print("mean:", df["GPA"].mean())
print("median:", df["GPA"].median())
print("mode:", df["GPA"].mode().tolist())
print("min:", df["GPA"].min())
print("max:", df["GPA"].max())
print("std:", df["GPA"].std())

display(df.describe())

mean: 3.2142857142857144
median: 3.2
mode: [2.5, 2.9, 3.1, 3.2, 3.4, 3.6, 3.8]
min: 2.5
max: 3.8
std: 0.4375255094603872

            GPA  Hours_Studied  GPA_rounded
count  7.000000       7.000000     7.000000
mean   3.214286      10.000000     3.142857
std    0.437526       3.162278     0.690066
min    2.500000       5.000000     2.000000
25%    3.000000       8.500000     3.000000
50%    3.200000      10.000000     3.000000
75%    3.500000      11.500000     3.500000
max    3.800000      15.000000     4.000000

## Grouping

In [35]:

avg_gpa_by_major = df.groupby("Major")["GPA"].mean().reset_index(name="Avg_GPA")
display(avg_gpa_by_major)

     Major  Avg_GPA
0       CS     3.00
1     Math     3.70
2  Physics     3.05


## Summary
- `pd.Series` and `pd.DataFrame` are core pandas objects.
- Use `.loc` for label-based and `.iloc` for position-based selection.
- Always select with `[rows, columns]` when slicing tables.
- Filter rows with boolean conditions.
- Create or transform columns for analysis.
- Compute descriptive statistics and group summaries.